### ISSUE TITLE
Some content is not shown correctly for example for tr  command

### ISSUE THREAD

**Issue by kaifricke** [benwaffle/doc#4]
When running doc with tr command, some lines are rendered blank
Everything between 

[:class:]
 Represents all characters belonging to the defined character class.  Class names are:
                alnum        \<alphanumeric characters\>
                alpha        \<alphabetic characters\>
                blank        \<whitespace characters\>
                cntrl        \<control charactersv>
                digit        \<numeric charactersv>
                graph        \<graphic characters\>
                ideogram     \<ideographic characters\>
                lower        \<lower-case alphabetic characters\>
                phonogram    \<phonographic characters\>
                print       \<printable charactersv>
                punct        \<punctuation characters\>
                rune         \<valid charactersv>
                space        \<space charactersv>
                special      \<special characters\>
                upper        \<upper-case characters\>
                xdigit       \<hexadecimal characters\>
                When [:lower:]
All classes are shown as blank lines.
It seems that the data is parsed correctly (as it is also in the ast jso dump). just not rendered correctly

**Comment by benwaffle** [comment]
Thanks, are you on macOS or Linux? Can you share the man file?

**Comment by kaifricke** [comment]
Hello, I am on the latest macOS (ARM64). man file is attached ( 
[tr.txt](https://github.com/benwaffle/doc/files/14019612/tr.txt)
).
 On Linux its rendered like the original, and the original man 
page there has to gt/lt chars.

**Comment by benwaffle** [comment]
This bug was fixed in 457d26c
